services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - db
    networks:
      - securevision_network

  frontend:
    build:
      context: frontend-test
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file: ".env"
    volumes:
      - docker:/entrypoint
    depends_on:
      - db
    networks:
      - securevision_network

  db:
    image: mysql:latest
    env_file: ".env"
    volumes:
      - db_data:/var/lib/mysql
    port:
      - "3306:3306"
    networks:
      - securevision_network

volumes:
  db_data:
networks:
  securevision_network:
    external: true

# data-ingestion:
#   build:
#     context: workers
#     dockerfile: ../docker/Dockerfile.data_ingestion
#   volumes:
#     - workers:/worker
#   deploy:
#     mode: replicated
#     replicas: 4
#   env_file: ".env"
#   depends_on:
#     - db
#   networks:
#     - securevision_network

# scanner:
#   build:
#     context: workers
#     dockerfile: ../docker/Dockerfile.scanner
#   volumes:
#     - worker:/worker
#   env_file: ".env"
#   deploy:
#     mode: replicated
#     replicas: 4
#   depends_on:
#     - db
#   networks:
#     - securevision_network
