"""add_risk_score_and_pattern_type

Revision ID: bbe39c372d66
Revises: 
Create Date: 2025-01-18 21:49:29.723281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe39c372d66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breach_entries', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('breach_entries', sa.Column('pattern_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('breach_entries', 'pattern_type')
    op.drop_column('breach_entries', 'risk_score')
    # ### end Alembic commands ###
